### ISSUE TITLE
fsverity-utils on CI build

### ISSUE THREAD

**Issue by embetrix** [ebiggers/fsverity-utils#2]
Hello,

the fsverity-utils signing requires a running kernel with fsverity support and root right to inject the keys through keyctl which make it impossible to use in a CI Build e.g docker container !

would be a possible to change this behaviour ? IMA/EVM and DMverity do not have this restriction.

**Comment by ebiggers** [comment]
I don't see any problem, so I'm closing this issue.  If you have more details, please reopen (or preferably, report to the fsverity mailing list which is where bug reports are supposed to go) and give more details.
